name: Security Vulnerability
description: Report a security vulnerability (PRIVATE - will not be publicly visible)
title: "[SECURITY]: "
labels: ["security", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT: Do not disclose security vulnerabilities publicly!**

        Please report security vulnerabilities through:
        1. GitHub Security Advisory: https://github.com/hyperpolymath/polyglot-i18n/security/advisories/new
        2. Or email the maintainers privately

        This form is for tracking purposes only. Critical vulnerabilities should be reported privately first.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this vulnerability?
      options:
        - Critical (allows remote code execution, data breach)
        - High (allows unauthorized access, XSS)
        - Medium (DoS, information disclosure)
        - Low (minor security concern)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the vulnerability
      placeholder: What is the security issue?
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the potential impact of this vulnerability?
      placeholder: An attacker could...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be reproduced?
      placeholder: |
        1. Configure i18n with...
        2. Send malicious input...
        3. Observe security issue...

  - type: textarea
    id: poc
    attributes:
      label: Proof of Concept
      description: Provide a proof of concept (if safe to share)
      render: javascript

  - type: input
    id: version
    attributes:
      label: Affected Versions
      description: Which versions are affected?
      placeholder: "0.15.x, 0.14.x"
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for fixing this?
      placeholder: This could be fixed by...

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to CVEs, security advisories, etc.
      placeholder: CVE-XXXX-XXXX, OWASP reference, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have verified this is a legitimate security vulnerability
          required: true
        - label: I have NOT publicly disclosed this vulnerability
          required: true
        - label: I have reviewed SECURITY.md
          required: true
